### ISSUE TITLE
Adding Birthday/Anniversary Questions to the Quiz

### ISSUE THREAD

**Issue by esocha13** [Bgorson/giftology#106]
After the user selects Myself, Relative, or Friend and answers the Name question, the user should be prompted for a date in the format MM/DD but no year.

After the user selects Anniversary, the user should be prompted for a date in the format MM/DD but no year.

**Comment by Bgorson** [comment]
I've added this when a user selects birthday or anniversary.. which I think is what we're asking for here? Trying not to disrupt the flow too much since its not 'critical' information
