### ISSUE TITLE
Mobile Buttons

### ISSUE THREAD

**Issue by esocha13** [Bgorson/giftology#112]
I'm on iOS. Buttons are blue on mobile instead of black, and when you click a button twice it does not automatically unselect it until you start to scroll around.

**Comment by esocha13** [comment]
![iOS Mobile Quiz Buttons](https://github.com/Bgorson/giftology/assets/94810872/72b8a2b3-3f78-4230-83f3-08caf252e8d9)

**Comment by Bgorson** [comment]
should now be fixed

**Comment by Bgorson** [comment]
more explicitly selecting the background color now which should fix this
