### ISSUE TITLE
Mobile Card Button Outline

### ISSUE THREAD

**Issue by esocha13** [Bgorson/giftology#117]
On iOS mobile, the Add to Wishlist and Info buttons do not have a black outline

**Comment by esocha13** [comment]
![Outline Missing on IOS](https://github.com/Bgorson/giftology/assets/94810872/baf26ccd-f5b0-4442-83ab-a54277ff568b)

**Comment by Bgorson** [comment]
possibly fixed now

**Comment by Bgorson** [comment]
update isn't pushed yet- just making notes on what is in the PR

**Comment by esocha13** [comment]
Working but Add to Wishlist is leaving the frame of the card

**Comment by Bgorson** [comment]
should be fixed in the next update
