### ISSUE TITLE
Gender Question

### ISSUE THREAD

**Issue by esocha13** [Bgorson/giftology#128]
Add a new question, which should be the new question 2 following "who are you shopping for?" Updated quiz counter to be a maximum of 8 quiz slides.

Are you/they:
Male
Female
Non-Binary

**Comment by Bgorson** [comment]
added transgender based off some general best practice

**Comment by esocha13** [comment]
My issue here is I'm not sure feeding transgender in to the algorithm is going to be useful. What if we change the question to be "How do they identify?"

**Comment by Bgorson** [comment]
Why would it not be useful and how is that different?

**Comment by esocha13** [comment]
I'm cool to go with Other and Prefer Not to Answer, but just to close out my reasoning. ChatGPT gives different responses when you give it male/female. From the user perspective, if they are filling out that question they are likely to want gifts that align with the person's identity. If you are buying for a transgender girl, do you want gifts for someone who is trans or someone who is a girl? It's a sensitive topic so we've got to ride the line between giving the user the option they want while still being inclusive.
