### ISSUE TITLE
Issue with View Retailer Clicks

### ISSUE THREAD

**Issue by esocha13** [Bgorson/giftology#132]
We may not be tracking all our affiliate clicks. Historically they've been a little off, but only by a couple of clicks. This is a big gap, and I'm inclined to believe Amazon, particularly because Amazon should be the minimum, our site also has Etsy clicks.

From Google Analytics we got View Retailers clicks for: 
7/23 - 2 
7/24 - 8
7/25 - 3
7/26 - 4
7/27 - 3
7/28 - 7
7/29 - 2
Total - 29

But from Amazon:
7/23 - 5 
7/24 - 17
7/25 - 2
7/26 - 6
7/27 - 4
7/28 - 23
7/29 - 2
Total - 59

**Comment by Bgorson** [comment]
Fix is up and also might have resolved more analytics issues
