### ISSUE TITLE
Introduce Output Text on Results Page.

### ISSUE THREAD

**Issue by esocha13** [Bgorson/giftology#133]
I'd like to start including some output text above the affiliate disclosure on the results page. This is effectively just a mad-libs of the quiz question, the goal is to start making the product feel conversational.

Italicize the affiliate disclosure, but otherwise make it the same font, it seems a little chunky right now.

Figma Frame 12 as an example:

"Here are gift suggestions for a girl aged 12-17 who enjoys camping and outdoor games, and has interests in coffee, tea, and dogs. Be sure to add items to your wishlist, and create a profile so you can visit again and again!

Affiliate Disclosure: We may receive a commission on purchases made through the links on this page."

**Comment by Bgorson** [comment]
this is done.. but I'm not sure the terminology is the greatest... we might want to consider reworking this. Trying to make it like a readable sentence is going to be very clunky

**Comment by esocha13** [comment]
Ah, I didn't think you were going to get to this one for a while. Could you take it down until we have a chance to workshop it?

**Comment by esocha13** [comment]
Closing this one as well until we can talk through design live.
