### ISSUE TITLE
Add "missing the mark" Post-Quiz card

### ISSUE THREAD

**Issue by esocha13** [Bgorson/giftology#144]
Create our first Post-Quiz card. Based on our Figma link, create the card that says "Am I missing the mark? What can I do better?" This card should appear after the 15th product card. It has identical dimensions to product cards.

pricier
i'm just browsing
cheaper
bad suggestions
mix it up!
missing interests
more thoughtful
more customizable

https://www.figma.com/file/G7bw1j5EpK3JCwU4jk8C7N/Giftology-Home-Page-v1?type=design&node-id=0-1&mode=design&t=60qHb4vpB4hKJIs4-0

**Comment by Bgorson** [comment]
added 15 and 30th position cards

**Comment by esocha-rhino** [comment]
Alright those cards are in there. Is it possible to make Missing the Mark clickable, as in the buttons respond to feedback by changing color just like the quiz? Are those interactions being saved?

**Comment by esocha13** [comment]
Alright those cards are in there. Is it possible to make Missing the Mark clickable, as in the buttons respond to feedback by changing color just like the quiz? Are those interactions being saved?

**Comment by Bgorson** [comment]
Yea. I can put some interactions there. Right now it's being fed into Google analytics
