### ISSUE TITLE
Null Data Type to Boolean

### ISSUE THREAD

**Issue by esocha13** [Bgorson/giftology#148]
We should double check with Susie, but these three fields should switch to boolean instead of the nulls.

/*Fields should be boolean*/
SELECT 
pub.clicked_favorite
,pub.clicked_info
,pub.clicked_retailer
FROM public.user_behaviors pub

**Comment by esocha13** [comment]
One other option than Boolean, there could be uses cases where having the number of clicks makes sense, as in a user coming back to the view retailer button days apart.

**Comment by Bgorson** [comment]
fixed
