### ISSUE TITLE
Max of 1 click button registers if a user is not logged in

### ISSUE THREAD

**Issue by esocha13** [Bgorson/giftology#150]
If users are not logged in the site only registers one of their button clicks, I believe it is whichever is first. So if a user clicks the info button, wishlist button, and view retailer button, it only flips clicked_info to true.

Test Quiz Browser: c570aadb-ca6d-4e5c-ae5c-d4e1f999eed9
Test Quiz Mobile: 4316f457-60f9-4c61-97cc-938171812095

**Comment by Bgorson** [comment]
This is fixed
