### ISSUE TITLE
Profiles are not being saved

### ISSUE THREAD

**Issue by esocha13** [Bgorson/giftology#151]
I've tried different combinations, both logged out and logged in, but I cannot get the system to save new profiles.

**Comment by Bgorson** [comment]
This is fixed and should be tested

**Comment by esocha-rhino** [comment]
Good news bad news on this one. 

Profiles are now being saved, but they cannot be removed from the profiles menu.
In the event a user is not logged in, then hits a Favorites button prompting a login, that item is not favorited.
In the event a user is not logged in, then hits a Favorites button, none of the clicks are registering in the data. Doesn't matter if it's the Favorites, Info, or Retail button, none of the clicks data is saved.

**Comment by esocha13** [comment]
Good news bad news on this one.

Profiles are now being saved, but they cannot be removed from the profiles menu.
In the event a user is not logged in, then hits a Favorites button prompting a login, that item is not favorited.
In the event a user is not logged in, then hits a Favorites button, none of the clicks are registering in the data. Doesn't matter if it's the Favorites, Info, or Retail button, none of the clicks data is saved.
